name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Criar zip do projeto
        run: zip projeto.zip main.py README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: projeto
          path: projeto.zip
