name: Continuos Delivery
on:
  push:
    branches:
      - main # ou qualquer outro tipo de branch
jobs:
  deliver:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
            name: projeto.zip
            path: |
              main.py
              README.md
