name: Continuos Delivery
on:
  push:
    branches:
      - main # ou qualquer outro tipo de branch
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
            name: projeto.zip
            path: |
              main.py
              README.md
